export const quickBooksProductServiceNames = [
  "Accommodation",
  "Airline Ticket",
  "Car Rental",
  "Car Sales",
  "Car Search",
  "Catering Services",
  "Charge",
  "Container Insurance",
  "Delivery/Moving Service",
  "Design & Creative Services",
  "Dispatch",
  "Education",
  "Extra Hours",
  "Food and Beverage",
  "Holding Items",
  "Labor",
  "Labor/ per hour",
  "Meals and Entertainment",
  "Moving Service",
  "Photographic Services",
  "Product Purchasing",
  "Professional Language Solutions",
  "Rental Car",
  "Sales Tax",
  "Shipping",
  "Shipping and Delivery Services",
  "Shipping:Customs Paid Price",
  "Storage",
  "Support Services",
  "Transportation",
  "Travel",
  "Vehicle Sourcing & Exporting"
] as const;

export type QuickBooksProductServiceName = (typeof quickBooksProductServiceNames)[number];

export const quickBooksProductServiceItemIds: Record<QuickBooksProductServiceName, string> = {
  Accommodation: "18",
  "Airline Ticket": "115",
  "Car Rental": "68",
  "Car Sales": "66",
  "Car Search": "66",
  "Catering Services": "100",
  Charge: "56",
  "Container Insurance": "93",
  "Delivery/Moving Service": "19",
  "Design & Creative Services": "101",
  Dispatch: "87",
  Education: "27",
  "Extra Hours": "94",
  "Food and Beverage": "98",
  "Holding Items": "60",
  Labor: "63",
  "Labor/ per hour": "63",
  "Meals and Entertainment": "107",
  "Moving Service": "85",
  "Photographic Services": "105",
  "Product Purchasing": "15",
  "Professional Language Solutions": "1010000081",
  "Rental Car": "68",
  "Sales Tax": "1010000011",
  Shipping: "1010000021",
  "Shipping and Delivery Services": "1010000241",
  "Shipping:Customs Paid Price": "1010000051",
  Storage: "58",
  "Support Services": "1010000221",
  Transportation: "1010000031",
  Travel: "28",
  "Vehicle Sourcing & Exporting": "66"
};

export function getQuickBooksItemIdForProductService(name: QuickBooksProductServiceName) {
  return quickBooksProductServiceItemIds[name];
}
