export const quickBooksProductServiceNames = [
  "Accommodation",
  "Airline Ticket",
  "Car Rental",
  "Car Sales",
  "Car Search",
  "Catering Services",
  "Charge",
  "Container Insurance",
  "Delivery/Moving Service",
  "Design & Creative Services",
  "Dispatch",
  "Education",
  "Extra Hours",
  "Food and Beverage",
  "Holding Items",
  "Labor",
  "Labor/ per hour",
  "Meals and Entertainment",
  "Moving Service",
  "Photographic Services",
  "Product Purchasing",
  "Professional Language Solutions",
  "Rental Car",
  "Sales Tax",
  "Shipping",
  "Shipping and Delivery Services",
  "Shipping:Customs Paid Price",
  "Storage",
  "Support Services",
  "Transportation",
  "Travel",
  "Vehicle Sourcing & Exporting"
] as const;

export type QuickBooksProductServiceName = (typeof quickBooksProductServiceNames)[number];

export const quickBooksProductServiceItemIds: Record<QuickBooksProductServiceName, string> = {
  Accommodation: "11",
  "Airline Ticket": "114",
  "Car Rental": "51",
  "Car Sales": "65",
  "Car Search": "88",
  "Catering Services": "99",
  Charge: "55",
  "Container Insurance": "92",
  "Delivery/Moving Service": "16",
  "Design & Creative Services": "95",
  Dispatch: "86",
  Education: "26",
  "Extra Hours": "90",
  "Food and Beverage": "97",
  "Holding Items": "59",
  Labor: "61",
  "Labor/ per hour": "62",
  "Meals and Entertainment": "106",
  "Moving Service": "84",
  "Photographic Services": "104",
  "Product Purchasing": "14",
  "Professional Language Solutions": "1010000071",
  "Rental Car": "67",
  "Sales Tax": "1010000001",
  Shipping: "3",
  "Shipping and Delivery Services": "1010000231",
  "Shipping:Customs Paid Price": "1010000041",
  Storage: "57",
  "Support Services": "1010000211",
  Transportation: "45",
  Travel: "5",
  "Vehicle Sourcing & Exporting": "108"
};

export function getQuickBooksItemIdForProductService(name: QuickBooksProductServiceName) {
  return quickBooksProductServiceItemIds[name];
}
